### PR TITLE
Add SeasonWide property to ImagesSummary class

### PR DESCRIPTION
**Pull request by olsh**
Here is an example of such a response
https://api.thetvdb.com/series/253463/images

### CODE REVIEW

**Comment by HristoKolev** [comment]
Interesting. When was this added?

**Comment by olsh** [comment]
Who knows, but the property exists on the swagger page
https://api.thetvdb.com/swagger

**Comment by HristoKolev** [comment]
I will publish it this evening.

**Comment by HristoKolev** [comment]
Here is the thing, the endpoint has an inconsistent JSON output, for some properties when data is not available the value is null, other properties are just missing entirely if there is no data.

I read the changelog and it turns out that I had that property in the `ImagesSummary` before version `2.0.0`, but then I had removed it. Presumably because it stopped showing up in the responses.

**Comment by HristoKolev** [comment]
Published with v3.2.2.

If you find anything else missing or wrong, please open another issue. :)

**Pull request merged**
